server:
  port: 9502
spring:
  application:
    name: beta-service
management:
  endpoints:
    web:
      exposure:
        include: health, info, beans, mappings, env
eureka:
  instance:
    prefer-ip-address: true
    ip-address: ${spring.cloud.client.ip-address}
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
